- type: entity
  id: MREFabMachineBoard
  parent: [BaseMachineCircuitboard, BaseCommandContraband]
  name: M.R.E fabricator machine board
  description: A machine printed circuit board for an MRE fabricator.
  components:
  - type: MachineBoard
    prototype: MREFab
    stackRequirements:
      Manipulator: 4
      Steel: 5
      Plastic: 5
