- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleListeningPost
  name: Listening Post Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-lpo
    antagPrototype: ListeningPost
    exclusiveAntag: true
  - type: ListeningPostRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRoboNeuroticist
  name: Robo-Neuroticist Role
  components:
  - type: MindRole
    antagPrototype:  RoboNeuroticist
    exclusiveAntag: true
  - type: RoboNeuroticistRole
  - type: RoleBriefing
    briefing: roboneuroticist-role-briefing
