# SPDX-FileCopyrightText: 2025 Baine Junk <wym0n@proton.me>
# SPDX-FileCopyrightText: 2025 Bibble-B-Boop <mysticball8@gmail.com>
# SPDX-FileCopyrightText: 2025 JamboreeBot <JamboreeBot@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: loadout
  id: SubzeroJacks
  equipment:
    shoes: ClothingShoesBootsSubzeroHOS

- type: loadout
  id: SubzeroCoat
  equipment:
    outerClothing: ClothingOuterSubzeroHOS

- type: loadout
  id: HOSUshanka
  equipment:
   head: ClothingHeadHatUshankaHOS
