# SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: LockerGriffyFilled
  suffix: Filled
  parent: LockerGriffy
  components:
  - type: StorageFill
    contents:
      - id: MascotGriffySuit
      - id: MascotGriffyHead
      - id: GriffyPDA
      - id: PlushieGriffy
      - id: PaperSecurityGriffyManual
