- type: entity
  parent: MicrowaveMachineCircuitboard
  id: AdvancedMicrowaveMachineCircuitBoard
  name: advanced microwave machine board
  components:
  - type: MachineBoard
    prototype: AdvancedMicrowave
    stackRequirements:
      Manipulator: 3
      Glass: 5
      Cable: 6
